### ISSUE TITLE
Industry construction and others

### ISSUE THREAD

**Issue by rohithnair** [rohithnair/tier2ui#6]
Needs better categorization of construction companies as one user reported error seeing incorrect categorisation.

**Comment by rohithnair** [comment]
Could be due to companies house API returning a SOC code and not able to parse it or bucket it properly. needs refactoring code.

**Comment by rohithnair** [comment]
Adding new industries for a better search experience

Civil Engineering
Radio and Television
Computer Programming
Legal
Architecture
Scientific Research
Video or Music Production
Advertising
Vetenary,
Rental
Recruitment
Travel and Tourism
Security
Betting
Publishing
Software Publishing
Call Center
Medical
Dental
Care Home
Religious

**Comment by Fmlog** [comment]
Is this issue resolved?
I want to contribute

**Comment by rohithnair** [comment]
Hi @Fmlog I had a relook at it . It seems the API is sometimes not returning the SIC code. We couldn't do much about it and so the real companies house link was visited and the industry was picked from there. 
I have it in private repository; and is not public yet. Thanks for the shout out.
